on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v1.8.1
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.6'
    - run: raco pkg install --auto --batch crontab-lib/ crontab-test/ crontab/
    - run: raco test -j 4 crontab-test/
